### ISSUE TITLE
Display auth error messages on the sign-in component

### ISSUE THREAD

**Issue by axelbdt** [team-alembic/ash_authentication_phoenix#112]
[First discussed on Discord](https://discord.com/channels/711271361523351632/1068487121263919176)

In case of failed authentication, it should be possible to redirect to the sign-in route with the error message fitting nicely in the sign-in view.

Implementation considerations:
- Checking credentials with the Live View would be insecure. 
- Better to redirect and add a special kind of flash message that would be passed to the view.

**Comment by zachdaniel** [comment]
I think this should probably be the next thing we tackle. Dealt with this issue in realworld/twitter and pretty much anyone who uses this library at all will want to show an error message somewhere in the template at a minimum and not a flash message.

**Comment by sevenseacat** [comment]
This looks like it's already been addressed - on a failed sign-in (eg. credentials invalid) the error is now shown inline on the form.

<img width="418" alt="Screenshot 2023-11-13 at 12 16 55 pm" src="https://github.com/team-alembic/ash_authentication_phoenix/assets/543859/4940564c-48be-4f1e-8764-685d3d2530d8">

If there is other functionality that should be added, please re-open the issue!
