### ISSUE TITLE
Add the ability to customize the registration form with custom fields

### ISSUE THREAD

**Issue by guglielmobartelloni** [team-alembic/ash_authentication_phoenix#119]
Just as the title says: implement a way to add additional field in the registration form

**Comment by jimsynz** [comment]
Hi @guglielmobartelloni.

Thanks for taking the time to provide feedback.

You're right that it's not possible to do this at the moment, however the generated `:register_with_password` action is set up to accept any extra attributes passed to it. I've been scratching my head trying to figure out how to do this without opening a can of worms (input types, accessibility, etc) and I haven't thought of anything yet.  Keen for any feedback anyone has on how to do this.  In the mean time the best solution is to roll your own registration screen.

**Comment by allenwyma** [comment]
I got caught up in this. So we can override `:register_with_password` an this will be picked up by AAP (ash_authentication_phoenix)?

**Comment by zachdaniel** [comment]
It won't add additional fields to the view, no. The suggestion is to write your own registration live view or to push the gathering of additional fields to a step after sign up.

**Comment by zachdaniel** [comment]
There is a `register_with_password` action added to the user resource (IIRC that is what its called) You can poke around to see the action and its arguments with

```elixir
Ash.Resource.Info.actions(Resource) |> Enum.map(&(&1.name)) # to get the action names, so you can confirm it

Ash.Resource.Info.action(Resource, :name) # to see the action definition
```
