### ISSUE TITLE
2 errors found when going through the docs on ash-hq.org walkthrough

### ISSUE THREAD

**Issue by jedschneider** [team-alembic/ash_authentication_phoenix#127]
Hi folks, i successfully made it through the tutorial this morning [here](https://ash-hq.org/docs/guides/ash_authentication_phoenix/latest/tutorials/getting-started-with-ash-authentication-phoenix) with a couple of small fixes.

using `hex phx_new 1.7.0-rc.3`

## first error

I needed to update `gettext` to the following version to compile cleanly

```elixir
{:gettext, "~> 0.12.1"}
```

## the second error, more specific to this project:

I encountered the following compile error:

```
== Compilation error in file lib/ash_authentication_phoenix/components/sign_in.ex ==
** (CompileError) lib/ash_authentication_phoenix/components/sign_in.ex:146: AshAuthentication.Strategy.MagicLink.__struct__/0 is undefined, cannot expand struct AshAuthentication.Strategy.MagicLink. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code
    expanding struct: AshAuthentication.Strategy.MagicLink.__struct__/0
    lib/ash_authentication_phoenix/components/sign_in.ex:146: AshAuthentication.Phoenix.Components.SignIn.strategy_style/1
    (phoenix_live_view 0.18.15) expanding macro: Phoenix.Component.Declarative.__pattern__!/2
    lib/ash_authentication_phoenix/components/sign_in.ex:146: AshAuthentication.Phoenix.Components.SignIn.strategy_style/1
could not compile dependency :ash_authentication_phoenix, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ash_authentication_phoenix", update it with "mix deps.update ash_authentication_phoenix" or clean it with "mix deps.clean ash_authentication_phoenix"
```

I was able to solve by pointing at the previously released tag:

```elixir
{:ash_authentication_phoenix, git: "https://github.com/team-alembic/ash_authentication_phoenix.git", tag: "v1.4.8"},
```

I didn't investigate the magic link functionality to establish the root cause, but the tutorial specifies that most recent tag, so I think others might run into it as well?

thanks! this project is pretty cool and I really enjoyed having the walkthrough.

**Comment by sevenseacat** [comment]
I just went through the Getting Started guide and it looks like versions have been bumped since this issue was filed, so everything now works as it should!

Thanks for reporting the issue :)
