### ISSUE TITLE
Feat: Add (overridable) support for page titles

### ISSUE THREAD

**Issue by frankdugan3** [team-alembic/ash_authentication_phoenix#197]
It would be great to add page titles to the authentication routes, e.g.

```elixir
|> assign(:page_title, "Log In")
```

Ideally, these would be configurable via the override system.

If this sounds like a good idea, I'd be willing to work up a PR implementing it.

**Comment by zachdaniel** [comment]
Sounds good to me :D

**Comment by jimsynz** [comment]
![do it](https://media.giphy.com/media/RJERA4dW2m2ezM5Jpc/giphy.gif)

**Comment by ArthurClemens** [comment]
I've been looking into this. It appears that `RevertLive` is not being used, and that all forms are created inside `SignInLive`. 
Implementing `page_title` for `sign_in_route` is straightforward, but for `reset_route` something additional is needed that I can't figure out at the moment. 
The setup also leads to the `text` attribute to be reused on all auth pages, so it is not suited for use as heading.

**Comment by zachdaniel** [comment]
What is `RevertLive`?

**Comment by ArthurClemens** [comment]
Typo, should be `ResetLive`

**Comment by zachdaniel** [comment]
Yeah I'm not sure what that page is for. Maybe an artifact? @jimsynz

**Comment by BryanJBryce** [comment]
@zachdaniel @ArthurClemens It's the page that a user arrives on when they click the password reset link in their email: 
<img width="554" alt="image" src="https://github.com/team-alembic/ash_authentication_phoenix/assets/1293064/f9e16f15-fbac-4ee8-b3d3-72d2303c72a7">

**Comment by BryanJBryce** [comment]
`SignInLive` is a little confusing at first because it can lead you to think it's only for sign in, but it basically hosts any authentication strategy you configure in the user authentication configuration. I'd vote for a name change to `AuthLive` or something #namingishard

**Comment by ArthurClemens** [comment]
I figured so much after spending some time on SignInLive.
The problem I see is that the configuration options don't allow for different headings, info texts and page_title for the scenarios "sign in", "register", "reset password", where sign in and register can have variants for email/password and auth (I assume either/or and combined options).
Using (misusing?) the `Banner` config `text` to render a heading leads to the same heading on all pages. This makes it hard  to guide the user ("where am I?") or to incentivise to register ("You’re one click away from xyz").
There will be other wishes for with pages, and at some point it makes sense to create custom templates, but I think that ash_authentication can do more in bridging that gap.
Will follow up with a proposal for configurable screen texts.

**Comment by jimsynz** [comment]
There is relevant discussion in #236 you may want to share some of this there.
