### ISSUE TITLE
Incorrect identity_field configuration in password reset guide

### ISSUE THREAD

**Issue by xln7** [team-alembic/ash_authentication_phoenix#204]
https://ash-hq.org/docs/guides/ash_authentication_phoenix/latest/tutorials/getting-started-with-ash-authentication-phoenix#reset-password

identity_field(:unique_email) should be identity_field(:email)

**Comment by jimsynz** [comment]
![doh](https://media.giphy.com/media/26ueYUlPAmUkTBAM8/giphy.gif)
