### ISSUE TITLE
Attempting to register an account with an existing email address behaves unexpectedly

### ISSUE THREAD

**Issue by sevenseacat** [team-alembic/ash_authentication_phoenix#269]
Not sure if this is an issue with our app setup (which looks to be pretty default, according to the Getting Started docs) or with the lib itself.

Note: This doesn't happen with validations like length of password - they are rendered on the form as I would expect.

Steps to replicate:

* Have an existing user in the DB with a known email address
* Attempt to register a new account with the same email address

What I would expect to see:

* Some form of error rendered on the form (eg. GitHub has a "the email address is invalid or taken" message)

What actually happens:

* The failure action in the configured auth controller is called, which renders an "Authentication Failure" message. :(

**Comment by ahacking** [comment]
The problem is that this has security implications and can allow probing "does this user exist?"

Golden rule is to never provide a means to determine or differentiate between if a user exists but their password is wrong, vs an unknown user.

**Comment by sevenseacat** [comment]
I get that for login, but this is for registration.

**Comment by zachdaniel** [comment]
I think we should handle this, but we may need to make it opt-in behavior. The basic issue is that it's implemented with live view under the hood so adding rate limiting and other mitigation strategies might be harder to hook up (but not impossible). Would be worth seeing what `phx.gen.auth` does for this.

**Comment by jimsynz** [comment]
> I get that for login, but this is for registration.

it doesn't matter if it's for registration or sign up - it still allows an enumeration attack.

You are free to implement the `failure/3` in such a way that detects this situation.  Something like this would likely work fine:

```elixir
def failure(conn, {:password, :register}, changeset) when is_struct(changeset, Ash.Changeset) and changeset.valid? != true do
  # check for user already exists error on changeset
  conn
  |> put_flash(:error, "A user with that email address already exists")
  |> redirect(to: ~p"/my-register-route")
end

def failure(conn, _, _) do
  # default failure handler.
end
```

**Comment by zachdaniel** [comment]
So, having just added ash_authentication_phoenix to a new app, and trying to sign up with an email address I had used already and being greeted with this page:

![CleanShot 2023-09-17 at 14 54 59@2x](https://github.com/team-alembic/ash_authentication_phoenix/assets/5722339/58a0eed5-2a74-4b44-846c-5b81a79c094d)

I think we need to rethink the whole pattern of rendering an Authentication Failure page. I can't think of a single case where that would be the desired behavior. I think we need to build in a flash message + redirect into the default setup at a minimum. The *ideal* behavior I think would be a special kind of flash message that we render as though it was a form error (something we'd discussed in the past). Then to users it looks effectively the same. Although I do recall there was one major UX issue that caused us not to pursue that route which was the fact that the whole page blinked....

hold up. I think we can actually do the sign in token thing for sign ups, where we do the registration in the live view and issue a short lived sign in token. Then we won't have this issue at all.

**Comment by zachdaniel** [comment]
I would also put forward that just by getting a special page or an error for typing in certain emails that they can already enumerate the thing used to sign in. I'd go as far as to say that it is practically unavoidable. Likely the only thing that could solve for this in some way would be ip-based rate limiting and other bot/scripting related protections.

**Comment by zachdaniel** [comment]
With `sign_in_tokens_enabled?` set, the newest version now show this information on submit. Ultimately, it was always possible to enumerate emails/usernames using the sign in view, you'd just see which emails gave you back an error. To solve for this, you'd want to use some kind of rate limiting at the plug/conn level likely, or using an `on_mount` hook potentially if you wanted to do it at the LV level. You could also set up your own view and add a captcha or something similar.

**Comment by ahacking** [comment]
User enumeration is really _really_ to prevent.  Even doing the "forgot my password" can have different timing depending on if a user really was found and an email was sent, vs one that wasn't found with no email sent.  Its not that easy to make all cases indistinguishable with a sophisticated attacker, the best you can do is to not make it trivially obvious.

Another aspect to be careful with is password failures, when I looked at Ash Authentication there was no last failed, failure count, back-off or lock after N failures, which could permit password enumeration.

**Comment by zachdaniel** [comment]
Yep! Would be open to building those features in. With that said, it should be doable in user-land code via extending the actions with hooks.

**Comment by ahacking** [comment]
My view is that Ash should provide a set of core authentication support features but not necessarily a particular higher layer authentication solution.  An approach that is agnostic to but can be easily leveraged by various higher layer authentication solutions like Pow, Ueberauth, or phx.gen.auth (and having extensions for all of these is fine IMO).

So think just the resource parts that support token auth, account verification,  TOTP, external OIDC/OAUTH, WebAuthn, account auditing, credential reset/update, account back-off/lock policies.

I will look at contributing some code to Ash in the hope that some things may be useful/re-usable when I get over the current hump.
