### ISSUE TITLE
Google Auth: An unexpected success response was received

### ISSUE THREAD

**Issue by simpers** [team-alembic/ash_authentication_phoenix#298]
I'm trying to bootstrap a new project which will require an integration with Google to fetch Calendar API data.

Trying to set this up following the docs at AshAuthentication for Phoenix and LiveView.

I follow the default setup with a password strategy and an OAuth2 strategy for Google, where I made an app and configured the [Google Cloud Console - OAuth2 Consent](https://console.cloud.google.com/apis/credentials/consent), got the API secrets and whatnot.

The only non-default I have is that I put all the auth related routes under `/a` in my routes, just to scope them. This seems to not have broken anything but I thought I'd just mention this just in case.

Configuration in `User` resource:
```elixir
  @gcal_scopes [
      "profile",
      "email",
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/calendar.events",
      "https://www.googleapis.com/auth/calendar.events.readonly",
      "https://www.googleapis.com/auth/calendar.readonly",
      "https://www.googleapis.com/auth/calendar.settings.readonly",
    ]
    |> Enum.join(" ")

  ....

      oauth2 :google do
        registration_enabled? true
        client_id fn _, _ ->
            Lpe.Config.get_google_client_id()
          end
        client_secret fn _, _ ->
            Lpe.Config.get_google_client_secret()
          end

        redirect_uri "http://localhost:4000/a/auth"
        identity_resource UserIdentity
        site "https://accounts.google.com/o/oauth2/auth"
        authorize_url "https://accounts.google.com/o/oauth2/auth"
        auth_method :client_secret_post
        token_url "https://oauth2.googleapis.com/token"
        user_url "https://accounts.google.com/o/oauth2/auth"
        authorization_params access_type: "offline",
                             scope: @gcal_scopes
      end
```

After setting up the secrets I go to the auth route and I can see a login form for the password strategy, and I see the "Sign in with Google" button.

When I press the button and follow the instructions to *successfully* login, I get to the default "Authentication Error" page. In the terminal I get this WARNING log indicating an error but which was `An unexpected success response`:
```elixir
[warning] | file=lib/lpe_web/controllers/auth_controller.ex line=23 mfa=LpeWeb.AuthController.failure/3 remote_ip=127.0.0.1 request_id=F4vWJ6hmzxqXfYQAABKi [15:25:50.714]: Google auth failure?
Activity:	{:google, :callback}
Reason:	%Assent.RequestError{
  message: "An unexpected success response was received:\n\n\"<HTML>\\n<HEAD>\\n<TITLE>Moved Temporarily</TITLE>\\n</HEAD>\\n<BODY BGCOLOR=\\\"#FFFFFF\\\" TEXT=\\\"#000000\\\">\\n<H1>Moved Temporarily</H1>\\nThe document has moved <A HREF=\\\"https://accounts.google.com/signin/oauth/error?authError=Cg9pbnZhbGlkX3JlcXVlc3QSLFJlcXVpcmVkIHBhcmFtZXRlciBpcyBtaXNzaW5nOiByZXNwb25zZV90eXBlGjdodHRwczovL2RldmVsb3BlcnMuZ29vZ2xlLmNvbS9pZGVudGl0eS9wcm90b2NvbHMvb2F1dGgyIJAD\\\">here</A>.\\n</BODY>\\n</HTML>\\n\"\n",
  error: :unexpected_response
}
```

Following the link in the log takes me to a Google Auth error page that allows me to see the "details". It says it is a bad request. How what was bad with it, though. And that's where I get stuck. Not sure what I can do to untangle this.

Are there some AshAuthentication-specific examples on how to integrate with Google?

**Comment by jimsynz** [comment]
I see that you're setting the redirect URI to `"http://localhost:4000/a/auth"` - some providers don't allow callbacks to take place via HTTP.  I'm not sure if that's the case for Google or not, but you may want to try using an HTTPS reverse proxy such as [ngrok](https://ngrok.com/) to make sure.

Additionally, we use `assent` under the hood. You may want to look at [their Google strategy](https://github.com/pow-auth/assent/blob/main/lib/assent/strategies/google.ex) for some inspo.

Hope that helps.

**Comment by simpers** [comment]
> I see that you're setting the redirect URI to `"http://localhost:4000/a/auth"` - some providers don't allow callbacks to take place via HTTP. I'm not sure if that's the case for Google or not, but you may want to try using an HTTPS reverse proxy such as [ngrok](https://ngrok.com/) to make sure.
> 
> Additionally, we use `assent` under the hood. You may want to look at [their Google strategy](https://github.com/pow-auth/assent/blob/main/lib/assent/strategies/google.ex) for some inspo.
> 
> Hope that helps.

I'll check that out. Some vendors do allow http for localhost though, so that would be a disappointment as I really wouldn't want to have to depend on ngrok (bad xp with that hah).

**Comment by lawik** [comment]
Could it be that the general Google Calendar access scope requires specific approval?

I am having something similar after adding a few scopes. Not sure why yet.

**Comment by simpers** [comment]
@jimsynz:
> I see that you're setting the redirect URI to `"http://localhost:4000/a/auth"` - some providers don't allow callbacks to take place via HTTP. I'm not sure if that's the case for Google or not, but you may want to try using an HTTPS reverse proxy such as [ngrok](https://ngrok.com/) to make sure.

So I tested this today and there's no difference. I had no reason to think it would change anything as Google didn't complain about HTTP, but just wanted to make sure. I get the same issue.

> Additionally, we use `assent` under the hood. You may want to look at [their Google strategy](https://github.com/pow-auth/assent/blob/main/lib/assent/strategies/google.ex) for some inspo.

Yeah, I already checked that out. It's not really giving any useful information regarding this.

@lawik:
> Could it be that the general Google Calendar access scope requires specific approval?
> 
> I am having something similar after adding a few scopes. Not sure why yet.

That's interesting! I'll try to remove them and see if that changes anything.

This is the final screen I get before encountering the default "Authentication error"-page:
![Screenshot 2023-10-16 at 13 25 40](https://github.com/team-alembic/ash_authentication_phoenix/assets/5390371/f71cab49-9857-455a-a426-3e4c02dc5c7e)

**Comment by simpers** [comment]
I only have the scopes "profile email" in my current code, and I still get this error:
```elixir
[warning] | file=lib/lpe_web/controllers/auth_controller.ex line=23 mfa=LpeWeb.AuthController.failure/3 remote_ip=127.0.0.1 request_id=F5dUUmSQiBaUSQkAAAvh [01:01:37.368]: Google auth failure?
Activity:       {:google, :callback}
Reason: %Assent.RequestError{
  message: "An unexpected success response was received:\n\n\"<HTML>\\n<HEAD>\\n<TITLE>Moved Temporarily</TITLE>\\n</HEAD>\\n<BODY BGCOLOR=\\\"#FFFFFF\\\" TEXT=\\\"#000000\\\">\\n<H1>Moved Temporarily</H1>\\nThe document has moved <A HREF=\\\"https://accounts.google.com/signin/oauth/error?authError=Cg9pbnZhbGlkX3JlcXVlc3QSLFJlcXVpcmVkIHBhcmFtZXRlciBpcyBtaXNzaW5nOiByZXNwb25zZV90eXBlGjdodHRwczovL2RldmVsb3BlcnMuZ29vZ2xlLmNvbS9pZGVudGl0eS9wcm90b2NvbHMvb2F1dGgyIJAD\\\">here</A>.\\n</BODY>\\n</HTML>\\n\"\n",
  error: :unexpected_response
}
```

The base64 decoded error is: `invalid_request,Required parameter is missing: response_type7https://developers.google.com/identity/protocols/oauth2`
Which also shows in the below:
<img width="476" alt="Screenshot 2023-11-14 at 01 06 00" src="https://github.com/team-alembic/ash_authentication_phoenix/assets/5390371/5bf6b693-e659-4509-9c3f-c9149f7c33db">

**Comment by jimsynz** [comment]
Did anyone figure this out?

**Comment by simpers** [comment]
> Did anyone figure this out?

Yes, I did!

We talked about me providing a guide for this, as it was quite tricky. I have a working example with Ash pre-3.0, can't remember exact version, but I am going to be bumping this and testing it out soon. And I need another integration for another project so I'll have to go through it all over again anyway, so I'll document it and provide the guide that way.

**Comment by jimsynz** [comment]
I ran through a google auth setup the other day with a client and had no issues, so I am guessing that this is related to the scopes?

**Comment by simpers** [comment]
It was something about the scopes' docs on Google being incorrect, as well as an outdated URL of some kind, so I had to find the proper ones by scouring other implementations and stuff. In my case I am asking for calendar access on top of just the user's profile.

Which scopes did you use?

**Comment by jimsynz** [comment]
Just whatever Assent's google strategy uses by default.

**Comment by simpers** [comment]
> Just whatever Assent's google strategy uses by default.

Yeah that worked fine for me too! The problem was adding the scopes for Google Calendar access.

I think my conclusion was something along the lines of:

_Ignore the error message google gives you because it steers you in the wrong direction – as the messages were about the type of client and which keys are valid for which client in the body's payload – when in reality it was about the format of the scopes._

I'll look at the code I made it work with, but only after I've gone through it all once again in a new project to see if I'll end up thinking the same. And if so, I'll make a PR for those possibly struggling with the same thing later – more scopes than the default for just authentication.
