### ISSUE TITLE
LiveView `put_flash` doesn't work within a component without a `push_navigate` or `push_patch`.

### ISSUE THREAD

**Issue by jimsynz** [team-alembic/ash_authentication_phoenix#323]

**Comment by sevenseacat** [comment]
This has to do with components having their own flash messages. It doesn't work a navigate either, eg. putting a `push_navigate` [here](https://github.com/team-alembic/ash_authentication_phoenix/blob/3c0a5960f323906ffe0e72dc41933c2a6eab7641/lib/ash_authentication_phoenix/components/password/reset_form.ex#L152-L157) still won't make the flash message display.

I wrote a blog post a while ago about this, and a pattern you can implement to send all flashes to the top-level LV for rendering - https://sevenseacat.net/posts/2023/flash-messages-in-phoenix-liveview-components/
