### ISSUE TITLE
The bit about "Customizing the generated routes" is not visible on hexdocs

### ISSUE THREAD

**Issue by yasoob** [team-alembic/ash_authentication_phoenix#356]
Hi all!

This [bit from the documentation](https://github.com/team-alembic/ash_authentication_phoenix/blob/main/documentation/tutorials/getting-started-with-ash-authentication-phoenix.md#customizing-the-generated-routes) is not visible on hexdocs. Is it because it didn't get deployed somehow?

<img width="1078" alt="image" src="https://github.com/team-alembic/ash_authentication_phoenix/assets/3696393/93f810a5-3520-471a-877c-1b27b1e6b2d0">

**Comment by zachdaniel** [comment]
A release hasn't been cut since that change was added. It will be published on the next release.

**Comment by zachdaniel** [comment]
I've published the latest version of the docs in the meantime.
