### ISSUE TITLE
support something similar to how return_to works for regular controllers 

### ISSUE THREAD

**Issue by simon-nystrom** [team-alembic/ash_authentication_phoenix#450]
When attempting to access an authenticated resource such as one like this:

```elixir
  ash_authentication_live_session :authentication_required,
    on_mount: {MyApp.LiveUserAuth, :live_user_required} do
    live "/protected", SomeView
  end
```

You successfully get redirected to the the sign in page, but once you sign in successfully there seems to be no easy way to figure out where you came from, and thus no easy way to redirect back to where your authentication failed

It would be great if there was an easy way to send the user back to where they were redirected from

**Comment by ahacking** [comment]
FYI. There is an example of doing this in the Ash Real-world app here: https://github.com/team-alembic/realworld/blob/main/lib/realworld_web/controllers/auth_controller.ex

A lot can be learned looking through that app.

**Comment by simon-nystrom** [comment]
Thanks ahacking, I realize now it wasn't apparent that I was referring to trying to get the same behaviour for LiveViews, what you've linked is actually what caused me to word this issue "similar to how return_to works for regular controllers"

**Comment by ahacking** [comment]
I have actually documented an approach in #484 that might be helpful until I have some time to work up a proper PR.
