### ISSUE TITLE
Unable to hide the SignIn banner

### ISSUE THREAD

**Issue by pehbehbeh** [team-alembic/ash_authentication_phoenix#475]
My auth overrides look like this:

```elixir
defmodule AppWeb.AuthOverrides do
  use AshAuthentication.Phoenix.Overrides

  override AshAuthentication.Phoenix.Components.SignIn do
    set :show_banner, false
    set :root_class, nil
  end
end

```

It is not possible to hide the banner, because `false` sets the value to `nil` and therefore [the default](https://github.com/team-alembic/ash_authentication_phoenix/blob/1114d929d2a0c7e613e894cf4d23f742db90b4e5/lib/ash_authentication_phoenix/components/sign_in.ex#L94) of `true` is used.

**Comment by zachdaniel** [comment]
I've pushed a fix PR, will wait for @jimsynz to take a look: https://github.com/team-alembic/ash_authentication_phoenix/pull/476

**Comment by pehbehbeh** [comment]
Thanks! 😍
