### ISSUE TITLE
Suggest adding how to implement "Return-To" support in the documentation or including support in the library

### ISSUE THREAD

**Issue by ahacking** [team-alembic/ash_authentication_phoenix#484]
I have made some minor changes to my router and controller to implement returning the user to the last path they tried accessing after successfully authenticating.

I thought it may be useful to fellow travelers or perhaps worth consideration for future inclusion into the library, given it is basically enabled with some minor changes:
* adding a one line function plug
* some convention for authentication routes / browser pipeline
* use of session ```:return_to``` in controller redirect

The strategy I use is based on the session and **not** using URI params as redirect URI's can be inadvertently bookmarked and also manipulated for [unchecked redirects / phishing scams](https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html).

In my router I group all the authentication paths under a common prefix to segregate from other app concerns and avoid the potential for recursive redirects via the ```:return_to``` plug on authentication paths.

lib/myapp_web/router.ex:
```elixir
...

# a common browser pipeline
pipeline :browser_common do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, html: {Web.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    # Ash authentication
    plug :load_from_session
end

pipeline :browser do
    plug :browser_common

    # use the return_to plug for non-authentication routes
    plug :return_to
end

scope "/auth", MyAppWeb do
    pipe_through :browser_common

    # put Ash Authentication routes here...
end

scope "/", MyAppWeb do
    pipe_through :browser

   # put MyApp browser routes and live sessions here ...
end

# function plug to stash GET paths into the session to return to after successful authentication
defp return_to(%Plug.Conn{method: "GET", request_path: path} = conn, _opts),
    do: put_session(conn, :return_to, path)
```

The AuthController just picks up the ``:return_to`` path from the session.  I attempt to return to the last set path even on a sign-out, so that when sign-in completes the user is returned right back to where they were. Some may prefer to always return to the home page depending on requirements, however it works well for forced session timeouts/sign-outs.

lib/myapp_web/controllers/auth_controller.ex:
```elixir
defmodule MyAppWeb.AuthController do
  use MyAppWeb, :controller
  use AshAuthentication.Phoenix.Controller

  def success(conn, _activity, user, _token) do
    path = return_path(conn)

    conn
    |> delete_session(:return_to)
    |> store_in_session(user)
    |> assign(:current_user, user)
    |> redirect(to: path)
  end

  def failure(conn, _activity, _reason) do
    conn
    |> put_flash(:error, "Incorrect email or password")
    |> redirect(to: ~p"/auth/sign-in")
  end

  def sign_out(conn, _params) do
    path = return_path(conn)

    conn
    |> clear_session()
    |> redirect(to: path)
  end

  defp return_path(conn), do: get_session(conn, :return_to) || ~p"/"
end
```

And of course make sure all your route paths in html and liveview mount hooks use the ``auth`` prefix, e.g.```~p"/auth/sign-in"```.

Hope this is useful to someone.

**Comment by zachdaniel** [comment]
This looks great 🥳 I'll close this issue since there isn't any specific thing to be done, but if you'd like to PR a guide on setting this up the way you have it, that would be great 🙇

**Comment by ahacking** [comment]
Sure I will work up a PR for this.
