### ISSUE TITLE
Dev/Test env differences for `on_mount` hooks passed to `ash_authentication_live_session`

### ISSUE THREAD

**Issue by modellurgist** [team-alembic/ash_authentication_phoenix#485]
Cross-posting this issue, in case you might have already observed a divergence in behavior between `test` and `dev` environments (i.e. if it's not a Wallaby issue): https://github.com/team-alembic/realworld/issues/8

**Comment by modellurgist** [comment]
Added more details to this separate issue on Wallaby repo, in case they have encountered anything like this:  https://github.com/elixir-wallaby/wallaby/issues/786

**Comment by zachdaniel** [comment]
Added comments here: https://github.com/team-alembic/realworld/issues/8

**Comment by zachdaniel** [comment]
Also, in the future, there is no need to cross post issues, and it can cause confusion/clutter. We monitor and manage both repos.
