### ISSUE TITLE
Inconsistent router helpers

### ISSUE THREAD

**Issue by totaltrash** [team-alembic/ash_authentication_phoenix#62]
Hey, minor quibble, but just wondering if there is a reason the `sign_in_route` and `sign_out_route` accept path arguments differently? One as an argument, the other as an option? Reckon they both could be options???

Current:

```elixir
    sign_in_route path: "/login"
    sign_out_route AuthController, "/logout"
```

Better?:

```elixir
    sign_in_route path: "/login"
    sign_out_route AuthController, path: "/logout"
```

**Comment by zachdaniel** [comment]
Makes sense. Would need to be a backwards compatible change (i.e a string should be treated as `path: String`, but thats easy enough to do. Feel free to make a PR also <3

**Comment by jimsynz** [comment]
Discussion moved to #236
