### ISSUE TITLE
Dark Mode bugs in /log-in

### ISSUE THREAD

**Issue by wintermeyer** [team-alembic/ash_authentication_phoenix#84]
**Describe the bug**

The text ist unreadably in dark mode and the Ash logo locks strange.

<img width="1093" alt="Bildschirm­foto 2023-01-29 um 21 16 06" src="https://user-images.githubusercontent.com/69770/215353600-084d63c4-5917-438d-a2cd-460c6cf6df06.png">

**To Reproduce**

Change your environment to dark mode and browse to http://localhost:4000/log-in

**Expected behavior**

Ideally the page would become a "proper" dark mode page with a dark background. But at least it should be usable. The text has to be readable.

<img width="1093" alt="Bildschirm­foto 2023-01-29 um 21 15 58" src="https://user-images.githubusercontent.com/69770/215353678-51e113e7-67b4-4e8c-b745-1efc4bcc4cda.png">

**Comment by zachdaniel** [comment]
I think we might just need to update the default for the sign in live root class:
```elixir
  override SignInLive do
    set :root_class, "grid h-screen place-items-center dark:bg-black"
  end
```
Adding `dark:bg-black` there. I fixed that in my app by updating my template.
