### ISSUE TITLE
/register route is missing

### ISSUE THREAD

**Issue by wintermeyer** [team-alembic/ash_authentication_phoenix#98]
There are the routes `/sign-in` and `/sign-out` but a `/register` route is missing. That would be very handy and cleaner from a user's perspective than the current way via the `/sign-in` route.

**Comment by jimsynz** [comment]
Just thinking out loud about what needs to happen to make this work:
 
1. We'd need to add a `supports_registration?` function to the `AshAuthentication.Strategy` protocol.
2. We'd need to make `sign_in_live` be able to filter strategies by whether or not it supports registration.
3. Do we generate a separate `registration_route` macro? How do we handle redirection between them?

**Comment by zachdaniel** [comment]
I wonder if it might be simpler as something like "components_for(route)". And then it can just render a link to the route? And then something like "ui_routes" callback

**Comment by jimsynz** [comment]
Yeah I'm thinking about something like an `AshAuthentication.Phoenix.Component` behaviour that can help figure out where and when to register specific components.
